# Generated by Django 4.2.3 on 2023-08-06 09:25

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jop',
            name='image',
            field=models.ImageField(upload_to=job.models.image_upload),
        ),
    ]
