# Generated by Django 4.2.3 on 2023-07-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jop_jop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
