# Generated by Django 4.2.3 on 2023-08-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
