# Generated by Django 4.2.3 on 2023-08-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_apply_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='cd',
            new_name='cv',
        ),
    ]
